"""add app status table for enginelight

Revision ID: 10aaa4625220
Revises: 3aba96e0a6ab
Create Date: 2015-05-19 22:19:48.978538

"""

# revision identifiers, used by Alembic.
revision = '10aaa4625220'
down_revision = '3aba96e0a6ab'

from alembic import op
import sqlalchemy as sa

import datetime

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    app_status = op.create_table('app_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # default to giving the app an OK status when we start
    op.bulk_insert(
        app_status,
        [
            { 'status': 'ok', 'last_updated': datetime.datetime.now(), 'message': None }
        ]
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_status')
    ### end Alembic commands ###
