"""domains table

Revision ID: 127951dab2d
Revises: 4cdcf068ef59
Create Date: 2015-11-02 17:28:51.653633

"""

# revision identifiers, used by Alembic.
revision = '127951dab2d'
down_revision = '4cdcf068ef59'

from alembic import op
import sqlalchemy as sa

"""domains table

Revision ID: 36a730c5724c
Revises: 4cdcf068ef59
Create Date: 2015-11-02 17:20:35.461571

"""

# revision identifiers, used by Alembic.
revision = '36a730c5724c'
down_revision = '4cdcf068ef59'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(sa.schema.Sequence("accepted_domains_id_seq")))
    accepted = op.create_table('accepted_domains',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, server_default=sa.text("nextval('accepted_domains_id_seq'::regclass)")),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='created_by_id_fkey', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='updated_by_id_fkey', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )

    op.bulk_insert(accepted, [
        {'domain': 'pittsburghpa.gov'},
    ])

    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accepted_domains')
    op.execute(sa.schema.DropSequence(sa.schema.Sequence("accepted_domains_id_seq")))
    ### end Alembic commands ###
