"""line item percentage flag, status max scrape

Revision ID: 1892291d723a
Revises: 3473ff14af7e
Create Date: 2015-05-27 13:11:47.655255

"""

# revision identifiers, used by Alembic.
revision = '1892291d723a'
down_revision = '3473ff14af7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_status', sa.Column('county_max_deadline', sa.DateTime(), nullable=True))
    op.add_column('line_item', sa.Column('percentage', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_item', 'percentage')
    op.drop_column('app_status', 'county_max_deadline')
    ### end Alembic commands ###
