"""Change contract property value to text type

Revision ID: 1abce90e550b
Revises: 20e5ee0480f6
Create Date: 2015-05-13 20:05:09.318604

"""

# revision identifiers, used by Alembic.
revision = '1abce90e550b'
down_revision = '20e5ee0480f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract_property', 'value', type_=sa.Text())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract_property', 'value', type_=sa.String(length=255))
    ### end Alembic commands ###
