"""add opportunity types

Revision ID: 2303f398cc0e
Revises: 409abb6abb99
Create Date: 2015-09-04 16:40:59.787504

"""

# revision identifiers, used by Alembic.
revision = '2303f398cc0e'
down_revision = '409abb6abb99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_type', sa.Column('allow_opportunities', sa.Boolean(), nullable=True))
    op.add_column('contract_type', sa.Column('opportunity_response_instructions', sa.Text(), nullable=True))
    op.create_foreign_key('created_by_id_fkey', 'job_status', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('updated_by_id_fkey', 'job_status', 'users', ['updated_by_id'], ['id'])
    op.add_column('opportunity', sa.Column('opportunity_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'opportunity_type_id_contract_type_id_fkey', 'opportunity', 'contract_type',
        ['opportunity_type_id'], ['id']
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('opportunity_type_id_contract_type_id_fkey', 'opportunity', type_='foreignkey')
    op.drop_column('opportunity', 'opportunity_type_id')
    op.drop_constraint('updated_by_id_fkey', 'job_status', type_='foreignkey')
    op.drop_constraint('created_by_id_fkey', 'job_status', type_='foreignkey')
    op.drop_column('contract_type', 'allow_opportunities')
    op.drop_column('contract_type', 'opportunity_response_instructions')
    ### end Alembic commands ###
