"""Split out contacts from company base model

Revision ID: 242a8bdd8fee
Revises: 534f16295a9b
Create Date: 2015-05-05 16:10:08.830992

"""

# revision identifiers, used by Alembic.
revision = '242a8bdd8fee'
down_revision = '534f16295a9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('addr1', sa.String(length=255), nullable=True),
    sa.Column('addr2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('fax_number', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'company', 'contact_state')
    op.drop_column(u'company', 'contact_city')
    op.drop_column(u'company', 'contact_last_name')
    op.drop_column(u'company', 'contact_zip')
    op.drop_column(u'company', 'contact_email')
    op.drop_column(u'company', 'contact_first_name')
    op.drop_column(u'company', 'contact_addr2')
    op.drop_column(u'company', 'contact_addr1')
    op.drop_column(u'company', 'contact_phone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'company', sa.Column('contact_phone', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(u'company', sa.Column('contact_addr1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(u'company', sa.Column('contact_addr2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(u'company', sa.Column('contact_first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(u'company', sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(u'company', sa.Column('contact_zip', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'company', sa.Column('contact_last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(u'company', sa.Column('contact_city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(u'company', sa.Column('contact_state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('company_contact')
    ### end Alembic commands ###
