"""Add department column to users model

Revision ID: 252e31376860
Revises: 4ade14e8244e
Create Date: 2015-05-08 15:53:46.935713

"""

# revision identifiers, used by Alembic.
revision = '252e31376860'
down_revision = '4ade14e8244e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=False, server_default="Other"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    ### end Alembic commands ###
