"""better nigp codes

Revision ID: 27c899412dc7
Revises: 2695fc68b01d
Create Date: 2015-07-09 13:23:06.551202

"""

# revision identifiers, used by Alembic.
revision = '27c899412dc7'
down_revision = '2695fc68b01d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'category', sa.Column('category_friendly_name', sa.Text(), nullable=True))
    op.add_column(u'category', sa.Column('examples', sa.Text(), nullable=True))
    op.add_column(u'category', sa.Column('examples_tsv', postgresql.TSVECTOR(), nullable=True))
    op.add_column(u'category', sa.Column('nigp_codes', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column(u'category', 'nigp_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'category', sa.Column('nigp_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column(u'category', 'nigp_codes')
    op.drop_column(u'category', 'examples_tsv')
    op.drop_column(u'category', 'examples')
    op.drop_column(u'category', 'category_friendly_name')
    ### end Alembic commands ###
