"""add flow archive flag

Revision ID: 2cc5046d4fae
Revises: 36a730c5724c
Create Date: 2015-11-03 11:14:36.852502

"""

# revision identifiers, used by Alembic.
revision = '2cc5046d4fae'
down_revision = '36a730c5724c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('updated_by_id_fkey', 'accepted_domains', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key('created_by_id_fkey', 'accepted_domains', 'users', ['created_by_id'], ['id'])
    op.add_column('flow', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'is_archived')
    op.drop_constraint('created_by_id_fkey', 'accepted_domains', type_='foreignkey')
    op.drop_constraint('updated_by_id_fkey', 'accepted_domains', type_='foreignkey')
    ### end Alembic commands ###
