"""empty message

Revision ID: 2d4ba8baa06c
Revises: 22427b19886b
Create Date: 2015-04-27 14:45:55.566462

"""

# revision identifiers, used by Alembic.
revision = '2d4ba8baa06c'
down_revision = '22427b19886b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    roles = op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_unique_constraint('company_company_name_key', 'company', ['company_name'])
    op.bulk_insert(roles, [
        { 'id': 1, 'name': 'superadmin' },
        { 'id': 2, 'name': 'admin' },
        { 'id': 3, 'name': 'staff' }
    ])
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_company_name_key', 'company', type_='unique')
    op.drop_table('users')
    op.drop_table('roles')
    ### end Alembic commands ###
