"""empty message

Revision ID: 36764b18f75f
Revises: 2d4ba8baa06c
Create Date: 2015-04-28 20:18:15.055689

"""

# revision identifiers, used by Alembic.
revision = '36764b18f75f'
down_revision = '2d4ba8baa06c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.alter_column('company', 'contact_second_name', new_column_name='contact_last_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'expiration_date')
    op.alter_column('company', 'contact_last_name', new_column_name='contact_second_name')
    ### end Alembic commands ###
