"""add starred association table

Revision ID: 37b62c1b2866
Revises: aee4d743e57
Create Date: 2015-06-06 23:10:45.415730

"""

# revision identifiers, used by Alembic.
revision = '37b62c1b2866'
down_revision = 'aee4d743e57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_starred_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_index(op.f('ix_contract_starred_association_contract_id'), 'contract_starred_association', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_starred_association_user_id'), 'contract_starred_association', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_starred_association_user_id'), table_name='contract_starred_association')
    op.drop_index(op.f('ix_contract_starred_association_contract_id'), table_name='contract_starred_association')
    op.drop_table('contract_starred_association')
    ### end Alembic commands ###
