"""add indices for all tables

Revision ID: 3aba96e0a6ab
Revises: 1abce90e550b
Create Date: 2015-05-18 23:40:57.850712

"""

# revision identifiers, used by Alembic.
revision = '3aba96e0a6ab'
down_revision = '1abce90e550b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=True)
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.drop_constraint(u'company_company_name_key', 'company', type_='unique')
    op.create_index(op.f('ix_company_contact_id'), 'company_contact', ['id'], unique=False)
    op.create_index(op.f('ix_company_contract_association_company_id'), 'company_contract_association', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_contract_association_contract_id'), 'company_contract_association', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_description'), 'contract', ['description'], unique=False)
    op.create_index(op.f('ix_contract_property_id'), 'contract_property', ['id'], unique=False)
    op.create_index(op.f('ix_contract_user_association_contract_id'), 'contract_user_association', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_user_association_user_id'), 'contract_user_association', ['user_id'], unique=False)
    op.create_index(op.f('ix_flow_id'), 'flow', ['id'], unique=False)
    op.create_index(op.f('ix_line_item_description'), 'line_item', ['description'], unique=False)
    op.create_index(op.f('ix_line_item_id'), 'line_item', ['id'], unique=False)
    op.create_index(op.f('ix_stage_id'), 'stage', ['id'], unique=False)
    op.create_index(op.f('ix_stage_property_id'), 'stage_property', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(u'users_email_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_stage_property_id'), table_name='stage_property')
    op.drop_index(op.f('ix_stage_id'), table_name='stage')
    op.drop_index(op.f('ix_line_item_id'), table_name='line_item')
    op.drop_index(op.f('ix_line_item_description'), table_name='line_item')
    op.drop_index(op.f('ix_flow_id'), table_name='flow')
    op.drop_index(op.f('ix_contract_user_association_user_id'), table_name='contract_user_association')
    op.drop_index(op.f('ix_contract_user_association_contract_id'), table_name='contract_user_association')
    op.drop_index(op.f('ix_contract_property_id'), table_name='contract_property')
    op.drop_index(op.f('ix_contract_description'), table_name='contract')
    op.drop_index(op.f('ix_company_contract_association_contract_id'), table_name='company_contract_association')
    op.drop_index(op.f('ix_company_contract_association_company_id'), table_name='company_contract_association')
    op.drop_index(op.f('ix_company_contact_id'), table_name='company_contact')
    op.create_unique_constraint(u'company_company_name_key', 'company', ['company_name'])
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    ### end Alembic commands ###
