"""more robust opportunities

Revision ID: 3c8dbc9ebf7e
Revises: 27c899412dc7
Create Date: 2015-07-24 19:32:29.608018

"""

# revision identifiers, used by Alembic.
revision = '3c8dbc9ebf7e'
down_revision = '27c899412dc7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('href', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_document_id'), 'opportunity_document', ['id'], unique=False)
    op.add_column(u'opportunity', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column(u'opportunity', sa.Column('planned_advertise', sa.DateTime(), nullable=False))
    op.add_column(u'opportunity', sa.Column('vendor_documents_needed', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.alter_column(u'opportunity', 'planned_deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column(u'opportunity', 'planned_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(u'opportunity_created_by_user_id_fkey', 'opportunity', type_='foreignkey')
    op.create_foreign_key('opportunity_created_by_id_user_id_fkey', 'opportunity', 'users', ['created_by_id'], ['id'])
    op.drop_column(u'opportunity', 'document_href')
    op.drop_column(u'opportunity', 'documents_needed')
    op.drop_column(u'opportunity', 'document')
    op.drop_column(u'opportunity', 'created_by')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'opportunity', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(u'opportunity', sa.Column('document', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(u'opportunity', sa.Column('documents_needed', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column(u'opportunity', sa.Column('document_href', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('opportunity_created_by_id_user_id_fkey', 'opportunity', type_='foreignkey')
    op.create_foreign_key(u'opportunity_created_by_user_id_fkey', 'opportunity', 'users', ['created_by'], ['id'])
    op.alter_column(u'opportunity', 'planned_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column(u'opportunity', 'planned_deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column(u'opportunity', 'vendor_documents_needed')
    op.drop_column(u'opportunity', 'planned_advertise')
    op.drop_column(u'opportunity', 'created_by_id')
    op.drop_index(op.f('ix_opportunity_document_id'), table_name='opportunity_document')
    op.drop_table('opportunity_document')
    ### end Alembic commands ###
