"""remove send_notifs flag

Revision ID: 3dcad2e19bc4
Revises: 3c8dbc9ebf7e
Create Date: 2015-08-04 16:00:32.260554

"""

# revision identifiers, used by Alembic.
revision = '3dcad2e19bc4'
down_revision = '3c8dbc9ebf7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'stage', 'send_notifs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'stage', sa.Column('send_notifs', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=False))
    ### end Alembic commands ###
