"""fix opportunities model

Revision ID: 3de73bde77e
Revises: 22cc439cd89
Create Date: 2015-06-25 00:55:51.895965

"""

# revision identifiers, used by Alembic.
revision = '3de73bde77e'
down_revision = '22cc439cd89'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_opportunity_association',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ondelete='SET NULL')
    )
    op.create_index(op.f('ix_category_opportunity_association_category_id'), 'category_opportunity_association', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_opportunity_association_opportunity_id'), 'category_opportunity_association', ['opportunity_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('form_href', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'document', ['id'], unique=False)
    op.add_column(u'opportunity', sa.Column('contact_id', sa.Integer(), nullable=False))
    op.add_column(u'opportunity', sa.Column('planned_deadline', sa.DateTime(), nullable=True))
    op.add_column(u'opportunity', sa.Column('planned_open', sa.DateTime(), nullable=True))
    op.add_column(u'opportunity', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column(u'opportunity', sa.Column('document', sa.String(length=255), nullable=True))
    op.add_column(u'opportunity', sa.Column('document_href', sa.String(length=255), nullable=True))
    op.add_column(u'opportunity', sa.Column('created_from_id', sa.Integer(), nullable=True))
    op.add_column(u'opportunity', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column(u'opportunity', sa.Column('documents_needed', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.create_foreign_key('opportunity_created_by_user_id_fkey', 'opportunity', 'users', ['created_by'], ['id'])
    op.drop_constraint(u'opportunity_category_id_fkey', 'opportunity', type_='foreignkey')
    op.create_foreign_key('opportunity_user_id_fkey', 'opportunity', 'users', ['contact_id'], ['id'])
    op.create_foreign_key('opportunity_contract_id_fkey', 'opportunity', 'contract', ['created_from_id'], ['id'])
    op.drop_column(u'opportunity', 'category_id')
    op.drop_column(u'opportunity', 'bid_open')
    op.drop_column(u'opportunity', 'contract_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'opportunity', sa.Column('bid_open', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column(u'opportunity', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'opportunity', sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('opportunity_user_id_fkey', 'opportunity', type_='foreignkey')
    op.create_foreign_key(u'opportunity_category_id_fkey', 'opportunity', 'category', ['category_id'], ['id'])
    op.drop_constraint('opportunity_created_by_user_id_fkey', 'opportunity', type_='foreignkey')
    op.drop_constraint('opportunity_contract_id_fkey', 'opportunity', type_='foreignkey')
    op.drop_column(u'opportunity', 'created_from_id')
    op.drop_column(u'opportunity', 'document_href')
    op.drop_column(u'opportunity', 'document')
    op.drop_column(u'opportunity', 'created_by')
    op.drop_column(u'opportunity', 'planned_open')
    op.drop_column(u'opportunity', 'planned_deadline')
    op.drop_column(u'opportunity', 'contact_id')
    op.drop_column(u'opportunity', 'is_public')
    op.drop_column(u'opportunity', 'documents_needed')
    op.drop_index(op.f('ix_category_opportunity_association_opportunity_id'), table_name='category_opportunity_association')
    op.drop_index(op.f('ix_category_opportunity_association_category_id'), table_name='category_opportunity_association')
    op.drop_table('category_opportunity_association')
    op.drop_index(op.f('ix_documents_id'), table_name='document')
    op.drop_table('document')
    ### end Alembic commands ###
