"""fix opportunities model

Revision ID: 3de73bde77e
Revises: 22cc439cd89
Create Date: 2015-06-25 00:55:51.895965

"""

# revision identifiers, used by Alembic.
revision = '3de73bde77e'
down_revision = '22cc439cd89'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_opportunity_association',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ondelete='SET NULL')
    )
    op.create_index(op.f('ix_category_opportunity_association_category_id'), 'category_opportunity_association', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_opportunity_association_opportunity_id'), 'category_opportunity_association', ['opportunity_id'], unique=False)
    op.add_column(u'opportunity', sa.Column('competitive_process_used', sa.String(length=255), nullable=True))
    op.add_column(u'opportunity', sa.Column('contact_id', sa.Integer(), nullable=False))
    op.add_column(u'opportunity', sa.Column('planned_deadline', sa.DateTime(), nullable=True))
    op.add_column(u'opportunity', sa.Column('planned_publish', sa.DateTime(), nullable=True))
    op.drop_constraint(u'opportunity_category_id_fkey', 'opportunity', type_='foreignkey')
    op.create_foreign_key('opportunity_user_id_fkey', 'opportunity', 'users', ['contact_id'], ['id'])
    op.drop_column(u'opportunity', 'category_id')
    op.drop_column(u'opportunity', 'bid_open')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'opportunity', sa.Column('bid_open', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column(u'opportunity', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('opportunity_user_id_fkey', 'opportunity', type_='foreignkey')
    op.create_foreign_key(u'opportunity_category_id_fkey', 'opportunity', 'category', ['category_id'], ['id'])
    op.drop_column(u'opportunity', 'planned_publish')
    op.drop_column(u'opportunity', 'planned_deadline')
    op.drop_column(u'opportunity', 'contact_id')
    op.drop_column(u'opportunity', 'competitive_process_used')
    op.drop_index(op.f('ix_category_opportunity_association_opportunity_id'), table_name='category_opportunity_association')
    op.drop_index(op.f('ix_category_opportunity_association_category_id'), table_name='category_opportunity_association')
    op.drop_table('category_opportunity_association')
    ### end Alembic commands ###
