"""Make contract/stage property key field non-nullable.

Revision ID: 409fc0730412
Revises: 36764b18f75f
Create Date: 2015-04-29 16:40:21.670588

"""

# revision identifiers, used by Alembic.
revision = '409fc0730412'
down_revision = '36764b18f75f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract_property', 'key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('stage_property', 'key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage_property', 'key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('contract_property', 'key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
