"""add category opportunity vendor models

Revision ID: 463e2275f99d
Revises: 3473ff14af7e
Create Date: 2015-05-27 14:45:05.170579

"""

# revision identifiers, used by Alembic.
revision = '463e2275f99d'
down_revision = '3473ff14af7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
