"""delete unused models

Revision ID: 4775567688de
Revises: 2cc5046d4fae
Create Date: 2015-11-05 14:01:29.610290

"""

# revision identifiers, used by Alembic.
revision = '4775567688de'
down_revision = '2cc5046d4fae'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_property')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vendor', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('contract_stage', 'notes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_table('stage_property',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stage_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], [u'users.id'], name=u'created_by_id_fkey'),
    sa.ForeignKeyConstraint(['stage_id'], [u'stage.id'], name=u'stage_property_stage_id_fkey', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], [u'users.id'], name=u'updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'stage_property_pkey')
    )
    op.add_column('contract_stage', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
