"""empty message

Revision ID: 4ade14e8244e
Revises: 242a8bdd8fee
Create Date: 2015-05-08 11:25:07.134567

"""

# revision identifiers, used by Alembic.
revision = '4ade14e8244e'
down_revision = '242a8bdd8fee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('financial_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'financial_id')
    ### end Alembic commands ###
