"""additional indexing

Revision ID: 4cdcf068ef59
Revises: 54373a7de91c
Create Date: 2015-10-22 19:58:41.145656

"""

# revision identifiers, used by Alembic.
revision = '4cdcf068ef59'
down_revision = '54373a7de91c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contract_current_stage_id'), 'contract', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_contract_department_id'), 'contract', ['department_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_department_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_current_stage_id'), table_name='contract')
    ### end Alembic commands ###
