"""user note relation

Revision ID: 501e2f945ff9
Revises: 3de73bde77e
Create Date: 2015-07-06 21:21:47.558753

"""

# revision identifiers, used by Alembic.
revision = '501e2f945ff9'
down_revision = '3de73bde77e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'contract_note', sa.Column('taken_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key('contract_note_user_id_fkey', 'contract_note', 'users', ['taken_by_id'], ['id'])
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.drop_index('ix_documents_id', table_name='document')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_id', 'document', ['id'], unique=False)
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_constraint('contract_note_user_id_fkey', 'contract_note', type_='foreignkey')
    op.drop_column(u'contract_note', 'taken_by_id')
    ### end Alembic commands ###
