"""empty message

Revision ID: 534f16295a9b
Revises: 409fc0730412
Create Date: 2015-04-30 17:56:51.510671

"""

# revision identifiers, used by Alembic.
revision = '534f16295a9b'
down_revision = '409fc0730412'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_user_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_user_association')
    ### end Alembic commands ###
