"""adding archive column to opp model

Revision ID: 54373a7de91c
Revises: 16e5b0c1ffc8
Create Date: 2015-10-20 10:46:05.956121

"""

# revision identifiers, used by Alembic.
revision = '54373a7de91c'
down_revision = '16e5b0c1ffc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        u'opportunity', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.schema.DefaultClause('false'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'opportunity', 'is_archived')
    ### end Alembic commands ###
