"""add percentage flag in line item model

Revision ID: 54e260a37a41
Revises: 3473ff14af7e
Create Date: 2015-05-27 01:55:53.665076

"""

# revision identifiers, used by Alembic.
revision = '54e260a37a41'
down_revision = '3473ff14af7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_item', sa.Column('percentage', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_item', 'percentage')
    ### end Alembic commands ###
