"""changes to allow biweekly digest

Revision ID: 8ac7c042469
Revises: 2303f398cc0e
Create Date: 2015-09-14 14:53:27.438500

"""

# revision identifiers, used by Alembic.
revision = '8ac7c042469'
down_revision = '2303f398cc0e'

from alembic import op
import sqlalchemy as sa

from purchasing.opportunities.models import Opportunity

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_status', sa.Column('last_beacon_newsletter', sa.DateTime(), nullable=True))
    op.add_column('opportunity', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('vendor', sa.Column('subscribed_to_newsletter', sa.Boolean(), nullable=False, server_default=sa.schema.DefaultClause('true')))
    ### end Alembic commands ###

    connection = op.get_bind()

    for opportunity in connection.execute('''select * from opportunity''').fetchall():
        if opportunity.is_public:
            connection.execute(Opportunity.__table__.update().where(
                Opportunity.__table__.c.id == opportunity.id
            ).values(
                published_at=opportunity.planned_publish
            ))

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'subscribed_to_newsletter')
    op.drop_column('opportunity', 'published_at')
    op.drop_column('app_status', 'last_beacon_newsletter')
    ### end Alembic commands ###
